#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if grep -q -E "(//|/\*|\*/|#)" $(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|jsx)$'); then
  echo "❌ Commit rejected: Comments found in staged files"
  echo "Please remove all comments before committing"
  exit 1
fi